// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEQXW7tBDvAMcucYObh8M4wX0Wd06IcIQ',
    appId: '1:389399881051:web:37883dd05d1a412e55267e',
    messagingSenderId: '389399881051',
    projectId: 'stage-2-techtorial',
    authDomain: 'stage-2-techtorial.firebaseapp.com',
    storageBucket: 'stage-2-techtorial.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlCNKvL7Jhdjk3n381DVCLhQXIvYi4dwo',
    appId: '1:389399881051:android:a0114e0ec463c09d55267e',
    messagingSenderId: '389399881051',
    projectId: 'stage-2-techtorial',
    storageBucket: 'stage-2-techtorial.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_xvsOscLReEQQC9pVYugthUYj0pRbisg',
    appId: '1:389399881051:ios:aedbda404c69b62255267e',
    messagingSenderId: '389399881051',
    projectId: 'stage-2-techtorial',
    storageBucket: 'stage-2-techtorial.firebasestorage.app',
    iosBundleId: 'com.example.stage2TechTorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_xvsOscLReEQQC9pVYugthUYj0pRbisg',
    appId: '1:389399881051:ios:aedbda404c69b62255267e',
    messagingSenderId: '389399881051',
    projectId: 'stage-2-techtorial',
    storageBucket: 'stage-2-techtorial.firebasestorage.app',
    iosBundleId: 'com.example.stage2TechTorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEQXW7tBDvAMcucYObh8M4wX0Wd06IcIQ',
    appId: '1:389399881051:web:eea2e2ded2c58ad555267e',
    messagingSenderId: '389399881051',
    projectId: 'stage-2-techtorial',
    authDomain: 'stage-2-techtorial.firebaseapp.com',
    storageBucket: 'stage-2-techtorial.firebasestorage.app',
  );

}